export interface CountryData {
  name: string;
  code: string; // ISO3
  iso2: string; // ISO2 for API lookups
  flag: string;
  currency: string; // Currency code (e.g. USD, INR, EUR)
}

export const GLOBAL_COUNTRIES: CountryData[] = [
  { name: 'Afghanistan', code: 'AFG', iso2: 'AF', flag: '🇦🇫', currency: 'AFN' },
  { name: 'Albania', code: 'ALB', iso2: 'AL', flag: '🇦🇱', currency: 'ALL' },
  { name: 'Algeria', code: 'DZA', iso2: 'DZ', flag: '🇩🇿', currency: 'DZD' },
  { name: 'Andorra', code: 'AND', iso2: 'AD', flag: '🇦🇩', currency: 'EUR' },
  { name: 'Angola', code: 'AGO', iso2: 'AO', flag: '🇦🇴', currency: 'AOA' },
  { name: 'Argentina', code: 'ARG', iso2: 'AR', flag: '🇦🇷', currency: 'ARS' },
  { name: 'Armenia', code: 'ARM', iso2: 'AM', flag: '🇦🇲', currency: 'AMD' },
  { name: 'Australia', code: 'AUS', iso2: 'AU', flag: '🇦🇺', currency: 'AUD' },
  { name: 'Austria', code: 'AUT', iso2: 'AT', flag: '🇦🇹', currency: 'EUR' },
  { name: 'Azerbaijan', code: 'AZE', iso2: 'AZ', flag: '🇦🇿', currency: 'AZN' },
  { name: 'Bahamas', code: 'BHS', iso2: 'BS', flag: '🇧🇸', currency: 'BSD' },
  { name: 'Bahrain', code: 'BHR', iso2: 'BH', flag: '🇧🇭', currency: 'BHD' },
  { name: 'Bangladesh', code: 'BGD', iso2: 'BD', flag: '🇧🇩', currency: 'BDT' },
  { name: 'Barbados', code: 'BRB', iso2: 'BB', flag: '🇧🇧', currency: 'BBD' },
  { name: 'Belarus', code: 'BLR', iso2: 'BY', flag: '🇧🇾', currency: 'BYN' },
  { name: 'Belgium', code: 'BEL', iso2: 'BE', flag: '🇧🇪', currency: 'EUR' },
  { name: 'Belize', code: 'BLZ', iso2: 'BZ', flag: '🇧🇿', currency: 'BZD' },
  { name: 'Benin', code: 'BEN', iso2: 'BJ', flag: '🇧🇯', currency: 'XOF' },
  { name: 'Bhutan', code: 'BTN', iso2: 'BT', flag: '🇧🇹', currency: 'BTN' },
  { name: 'Bolivia', code: 'BOL', iso2: 'BO', flag: '🇧🇴', currency: 'BOB' },
  { name: 'Bosnia and Herzegovina', code: 'BIH', iso2: 'BA', flag: '🇧🇦', currency: 'BAM' },
  { name: 'Botswana', code: 'BWA', iso2: 'BW', flag: '🇧🇼', currency: 'BWP' },
  { name: 'Brazil', code: 'BRA', iso2: 'BR', flag: '🇧🇷', currency: 'BRL' },
  { name: 'Brunei', code: 'BRN', iso2: 'BN', flag: '🇧🇳', currency: 'BND' },
  { name: 'Bulgaria', code: 'BGR', iso2: 'BG', flag: '🇧🇬', currency: 'BGN' },
  { name: 'Burkina Faso', code: 'BFA', iso2: 'BF', flag: '🇧🇫', currency: 'XOF' },
  { name: 'Burundi', code: 'BDI', iso2: 'BI', flag: '🇧🇮', currency: 'BIF' },
  { name: 'Cabo Verde', code: 'CPV', iso2: 'CV', flag: '🇨🇻', currency: 'CVE' },
  { name: 'Cambodia', code: 'KHM', iso2: 'KH', flag: '🇰🇭', currency: 'KHR' },
  { name: 'Cameroon', code: 'CMR', iso2: 'CM', flag: '🇨🇲', currency: 'XAF' },
  { name: 'Canada', code: 'CAN', iso2: 'CA', flag: '🇨🇦', currency: 'CAD' },
  { name: 'Central African Republic', code: 'CAF', iso2: 'CF', flag: '🇨🇫', currency: 'XAF' },
  { name: 'Chad', code: 'TCD', iso2: 'TD', flag: '🇹🇩', currency: 'XAF' },
  { name: 'Chile', code: 'CHL', iso2: 'CL', flag: '🇨🇱', currency: 'CLP' },
  { name: 'China', code: 'CHN', iso2: 'CN', flag: '🇨🇳', currency: 'CNY' },
  { name: 'Colombia', code: 'COL', iso2: 'CO', flag: '🇨🇴', currency: 'COP' },
  { name: 'Comoros', code: 'COM', iso2: 'KM', flag: '🇰🇲', currency: 'KMF' },
  { name: 'Congo', code: 'COG', iso2: 'CG', flag: '🇨🇬', currency: 'XAF' },
  { name: 'Costa Rica', code: 'CRI', iso2: 'CR', flag: '🇨🇷', currency: 'CRC' },
  { name: 'Croatia', code: 'HRV', iso2: 'HR', flag: '🇭🇷', currency: 'EUR' },
  { name: 'Cuba', code: 'CUB', iso2: 'CU', flag: '🇨🇺', currency: 'CUP' },
  { name: 'Cyprus', code: 'CYP', iso2: 'CY', flag: '🇨🇾', currency: 'EUR' },
  { name: 'Czechia', code: 'CZE', iso2: 'CZ', flag: '🇨🇿', currency: 'CZK' },
  { name: 'Denmark', code: 'DNK', iso2: 'DK', flag: '🇩🇰', currency: 'DKK' },
  { name: 'Djibouti', code: 'DJI', iso2: 'DJ', flag: '🇩🇯', currency: 'DJF' },
  { name: 'Dominica', code: 'DMA', iso2: 'DM', flag: '🇩🇲', currency: 'XCD' },
  { name: 'Dominican Republic', code: 'DOM', iso2: 'DO', flag: '🇩🇴', currency: 'DOP' },
  { name: 'Ecuador', code: 'ECU', iso2: 'EC', flag: '🇪🇨', currency: 'USD' },
  { name: 'Egypt', code: 'EGY', iso2: 'EG', flag: '🇪🇬', currency: 'EGP' },
  { name: 'El Salvador', code: 'SLV', iso2: 'SV', flag: '🇸🇻', currency: 'USD' },
  { name: 'Equatorial Guinea', code: 'GNQ', iso2: 'GQ', flag: '🇬🇶', currency: 'XAF' },
  { name: 'Eritrea', code: 'ERI', iso2: 'ER', flag: '🇪🇷', currency: 'ERN' },
  { name: 'Estonia', code: 'EST', iso2: 'EE', flag: '🇪🇪', currency: 'EUR' },
  { name: 'Eswatini', code: 'SWZ', iso2: 'SZ', flag: '🇸🇿', currency: 'SZL' },
  { name: 'Ethiopia', code: 'ETH', iso2: 'ET', flag: '🇪🇹', currency: 'ETB' },
  { name: 'Fiji', code: 'FJI', iso2: 'FJ', flag: '🇫🇯', currency: 'FJD' },
  { name: 'Finland', code: 'FIN', iso2: 'FI', flag: '🇫🇮', currency: 'EUR' },
  { name: 'France', code: 'FRA', iso2: 'FR', flag: '🇫🇷', currency: 'EUR' },
  { name: 'Gabon', code: 'GAB', iso2: 'GA', flag: '🇬🇦', currency: 'XAF' },
  { name: 'Gambia', code: 'GMB', iso2: 'GM', flag: '🇬🇲', currency: 'GMD' },
  { name: 'Georgia', code: 'GEO', iso2: 'GE', flag: '🇬🇪', currency: 'GEL' },
  { name: 'Germany', code: 'DEU', iso2: 'DE', flag: '🇩🇪', currency: 'EUR' },
  { name: 'Ghana', code: 'GHA', iso2: 'GH', flag: '🇬🇭', currency: 'GHS' },
  { name: 'Greece', code: 'GRC', iso2: 'GR', flag: '🇬🇷', currency: 'EUR' },
  { name: 'Grenada', code: 'GRD', iso2: 'GD', flag: '🇬🇩', currency: 'XCD' },
  { name: 'Guatemala', code: 'GTM', iso2: 'GT', flag: '🇬🇹', currency: 'GTQ' },
  { name: 'Guinea', code: 'GIN', iso2: 'GN', flag: '🇬🇳', currency: 'GNF' },
  { name: 'Guinea-Bissau', code: 'GNB', iso2: 'GW', flag: '🇬🇼', currency: 'XOF' },
  { name: 'Guyana', code: 'GUY', iso2: 'GY', flag: '🇬🇾', currency: 'GYD' },
  { name: 'Haiti', code: 'HTI', iso2: 'HT', flag: '🇭🇹', currency: 'HTG' },
  { name: 'Honduras', code: 'HND', iso2: 'HN', flag: '🇭🇳', currency: 'HNL' },
  { name: 'Hungary', code: 'HUN', iso2: 'HU', flag: '🇭🇺', currency: 'HUF' },
  { name: 'Iceland', code: 'ISL', iso2: 'IS', flag: '🇮🇸', currency: 'ISK' },
  { name: 'India', code: 'IND', iso2: 'IN', flag: '🇮🇳', currency: 'INR' },
  { name: 'Indonesia', code: 'IDN', iso2: 'ID', flag: '🇮🇩', currency: 'IDR' },
  { name: 'Iran', code: 'IRN', iso2: 'IR', flag: '🇮🇷', currency: 'IRR' },
  { name: 'Iraq', code: 'IRQ', iso2: 'IQ', flag: '🇮🇶', currency: 'IQD' },
  { name: 'Ireland', code: 'IRL', iso2: 'IE', flag: '🇮🇪', currency: 'EUR' },
  { name: 'Israel', code: 'ISR', iso2: 'IL', flag: '🇮🇱', currency: 'ILS' },
  { name: 'Italy', code: 'ITA', iso2: 'IT', flag: '🇮🇹', currency: 'EUR' },
  { name: 'Jamaica', code: 'JAM', iso2: 'JM', flag: '🇯🇲', currency: 'JMD' },
  { name: 'Japan', code: 'JPN', iso2: 'JP', flag: '🇯🇵', currency: 'JPY' },
  { name: 'Jordan', code: 'JOR', iso2: 'JO', flag: '🇯🇴', currency: 'JOD' },
  { name: 'Kazakhstan', code: 'KAZ', iso2: 'KZ', flag: '🇰🇿', currency: 'KZT' },
  { name: 'Kenya', code: 'KEN', iso2: 'KE', flag: '🇰🇪', currency: 'KES' },
  { name: 'Kiribati', code: 'KIR', iso2: 'KI', flag: '🇰🇮', currency: 'AUD' },
  { name: 'Kuwait', code: 'KWT', iso2: 'KW', flag: '🇰🇼', currency: 'KWD' },
  { name: 'Kyrgyzstan', code: 'KGZ', iso2: 'KG', flag: '🇰🇬', currency: 'KGS' },
  { name: 'Laos', code: 'LAO', iso2: 'LA', flag: '🇱🇦', currency: 'LAK' },
  { name: 'Latvia', code: 'LVA', iso2: 'LV', flag: '🇱🇻', currency: 'EUR' },
  { name: 'Lebanon', code: 'LBN', iso2: 'LB', flag: '🇱🇧', currency: 'LBP' },
  { name: 'Lesotho', code: 'LSO', iso2: 'LS', flag: '🇱🇸', currency: 'LSL' },
  { name: 'Liberia', code: 'LBR', iso2: 'LR', flag: '🇱🇷', currency: 'LRD' },
  { name: 'Libya', code: 'LBY', iso2: 'LY', flag: '🇱🇾', currency: 'LYD' },
  { name: 'Liechtenstein', code: 'LIE', iso2: 'LI', flag: '🇱🇮', currency: 'CHF' },
  { name: 'Lithuania', code: 'LTU', iso2: 'LT', flag: '🇱🇹', currency: 'EUR' },
  { name: 'Luxembourg', code: 'LUX', iso2: 'LU', flag: '🇱🇺', currency: 'EUR' },
  { name: 'Madagascar', code: 'MDG', iso2: 'MG', flag: '🇲🇬', currency: 'MGA' },
  { name: 'Malawi', code: 'MWI', iso2: 'MW', flag: '🇲🇼', currency: 'MWK' },
  { name: 'Malaysia', code: 'MYS', iso2: 'MY', flag: '🇲🇾', currency: 'MYR' },
  { name: 'Maldives', code: 'MDV', iso2: 'MV', flag: '🇲🇻', currency: 'MVR' },
  { name: 'Mali', code: 'MLI', iso2: 'ML', flag: '🇲🇱', currency: 'XOF' },
  { name: 'Malta', code: 'MLT', iso2: 'MT', flag: '🇲🇹', currency: 'EUR' },
  { name: 'Marshall Islands', code: 'MHL', iso2: 'MH', flag: '🇲🇭', currency: 'USD' },
  { name: 'Mauritania', code: 'MRT', iso2: 'MR', flag: '🇲🇷', currency: 'MRU' },
  { name: 'Mauritius', code: 'MUS', iso2: 'MU', flag: '🇲🇺', currency: 'MUR' },
  { name: 'Mexico', code: 'MEX', iso2: 'MX', flag: '🇲🇽', currency: 'MXN' },
  { name: 'Micronesia', code: 'FSM', iso2: 'FM', flag: '🇫🇲', currency: 'USD' },
  { name: 'Moldova', code: 'MDA', iso2: 'MD', flag: '🇲🇩', currency: 'MDL' },
  { name: 'Monaco', code: 'MCO', iso2: 'MC', flag: '🇲🇨', currency: 'EUR' },
  { name: 'Mongolia', code: 'MNG', iso2: 'MN', flag: '🇲🇳', currency: 'MNT' },
  { name: 'Montenegro', code: 'MNE', iso2: 'ME', flag: '🇲🇪', currency: 'EUR' },
  { name: 'Morocco', code: 'MAR', iso2: 'MA', flag: '🇲🇦', currency: 'MAD' },
  { name: 'Mozambique', code: 'MOZ', iso2: 'MZ', flag: '🇲🇿', currency: 'MZN' },
  { name: 'Myanmar', code: 'MMR', iso2: 'MM', flag: '🇲🇲', currency: 'MMK' },
  { name: 'Namibia', code: 'NAM', iso2: 'NA', flag: '🇳🇦', currency: 'NAD' },
  { name: 'Nauru', code: 'NRU', iso2: 'NR', flag: '🇳🇷', currency: 'AUD' },
  { name: 'Nepal', code: 'NPL', iso2: 'NP', flag: '🇳🇵', currency: 'NPR' },
  { name: 'Netherlands', code: 'NLD', iso2: 'NL', flag: '🇳🇱', currency: 'EUR' },
  { name: 'New Zealand', code: 'NZL', iso2: 'NZ', flag: '🇳🇿', currency: 'NZD' },
  { name: 'Nicaragua', code: 'NIC', iso2: 'NI', flag: '🇳🇮', currency: 'NIO' },
  { name: 'Niger', code: 'NER', iso2: 'NE', flag: '🇳🇪', currency: 'XOF' },
  { name: 'Nigeria', code: 'NGA', iso2: 'NG', flag: '🇳🇬', currency: 'NGN' },
  { name: 'North Korea', code: 'PRK', iso2: 'KP', flag: '🇰🇵', currency: 'KPW' },
  { name: 'North Macedonia', code: 'MKD', iso2: 'MK', flag: '🇲🇰', currency: 'MKD' },
  { name: 'Norway', code: 'NOR', iso2: 'NO', flag: '🇳🇴', currency: 'NOK' },
  { name: 'Oman', code: 'OMN', iso2: 'OM', flag: '🇴🇲', currency: 'OMR' },
  { name: 'Pakistan', code: 'PAK', iso2: 'PK', flag: '🇵🇰', currency: 'PKR' },
  { name: 'Palau', code: 'PLW', iso2: 'PW', flag: '🇵🇼', currency: 'USD' },
  { name: 'Palestine', code: 'PSE', iso2: 'PS', flag: '🇵🇸', currency: 'ILS' },
  { name: 'Panama', code: 'PAN', iso2: 'PA', flag: '🇵🇦', currency: 'PAB' },
  { name: 'Papua New Guinea', code: 'PNG', iso2: 'PG', flag: '🇵🇬', currency: 'PGK' },
  { name: 'Paraguay', code: 'PRY', iso2: 'PY', flag: '🇵🇾', currency: 'PYG' },
  { name: 'Peru', code: 'PER', iso2: 'PE', flag: '🇵🇪', currency: 'PEN' },
  { name: 'Philippines', code: 'PHL', iso2: 'PH', flag: '🇵🇭', currency: 'PHP' },
  { name: 'Poland', code: 'POL', iso2: 'PL', flag: '🇵🇱', currency: 'PLN' },
  { name: 'Portugal', code: 'PRT', iso2: 'PT', flag: '🇵🇹', currency: 'EUR' },
  { name: 'Qatar', code: 'QAT', iso2: 'QA', flag: '🇶🇦', currency: 'QAR' },
  { name: 'Romania', code: 'ROU', iso2: 'RO', flag: '🇷🇴', currency: 'RON' },
  { name: 'Russia', code: 'RUS', iso2: 'RU', flag: '🇷🇺', currency: 'RUB' },
  { name: 'Rwanda', code: 'RWA', iso2: 'RW', flag: '🇷🇼', currency: 'RWF' },
  { name: 'Saint Kitts and Nevis', code: 'KNA', iso2: 'KN', flag: '🇰🇳', currency: 'XCD' },
  { name: 'Saint Lucia', code: 'LCA', iso2: 'LC', flag: '🇱🇨', currency: 'XCD' },
  { name: 'Samoa', code: 'WSM', iso2: 'WS', flag: '🇼🇸', currency: 'WST' },
  { name: 'San Marino', code: 'SMR', iso2: 'SM', flag: '🇸🇲', currency: 'EUR' },
  { name: 'Sao Tome and Principe', code: 'STP', iso2: 'ST', flag: '🇸🇹', currency: 'STN' },
  { name: 'Saudi Arabia', code: 'SAU', iso2: 'SA', flag: '🇸🇦', currency: 'SAR' },
  { name: 'Senegal', code: 'SEN', iso2: 'SN', flag: '🇸🇳', currency: 'XOF' },
  { name: 'Serbia', code: 'SRB', iso2: 'RS', flag: '🇷🇸', currency: 'RSD' },
  { name: 'Seychelles', code: 'SYC', iso2: 'SC', flag: '🇸🇨', currency: 'SCR' },
  { name: 'Sierra Leone', code: 'SLE', iso2: 'SL', flag: '🇸🇱', currency: 'SLE' },
  { name: 'Singapore', code: 'SGP', iso2: 'SG', flag: '🇸🇬', currency: 'SGD' },
  { name: 'Slovakia', code: 'SVK', iso2: 'SK', flag: '🇸🇰', currency: 'EUR' },
  { name: 'Slovenia', code: 'SVN', iso2: 'SI', flag: '🇸🇮', currency: 'EUR' },
  { name: 'Solomon Islands', code: 'SLB', iso2: 'SB', flag: '🇸🇧', currency: 'SBD' },
  { name: 'Somalia', code: 'SOM', iso2: 'SO', flag: '🇸🇴', currency: 'SOS' },
  { name: 'South Africa', code: 'ZAF', iso2: 'ZA', flag: '🇿🇦', currency: 'ZAR' },
  { name: 'South Korea', code: 'KOR', iso2: 'KR', flag: '🇰🇷', currency: 'KRW' },
  { name: 'South Sudan', code: 'SSD', iso2: 'SS', flag: '🇸🇸', currency: 'SSP' },
  { name: 'Spain', code: 'ESP', iso2: 'ES', flag: '🇪🇸', currency: 'EUR' },
  { name: 'Sri Lanka', code: 'LKA', iso2: 'LK', flag: '🇱🇰', currency: 'LKR' },
  { name: 'Sudan', code: 'SDN', iso2: 'SD', flag: '🇸🇩', currency: 'SDG' },
  { name: 'Suriname', code: 'SUR', iso2: 'SR', flag: '🇸🇷', currency: 'SRD' },
  { name: 'Sweden', code: 'SWE', iso2: 'SE', flag: '🇸🇪', currency: 'SEK' },
  { name: 'Switzerland', code: 'CHE', iso2: 'CH', flag: '🇨🇭', currency: 'CHF' },
  { name: 'Syria', code: 'SYR', iso2: 'SY', flag: '🇸🇾', currency: 'SYP' },
  { name: 'Taiwan', code: 'TWN', iso2: 'TW', flag: '🇹🇼', currency: 'TWD' },
  { name: 'Tajikistan', code: 'TJK', iso2: 'TJ', flag: '🇹🇯', currency: 'TJS' },
  { name: 'Tanzania', code: 'TZA', iso2: 'TZ', flag: '🇹🇿', currency: 'TZS' },
  { name: 'Thailand', code: 'THA', iso2: 'TH', flag: '🇹🇭', currency: 'THB' },
  { name: 'Timor-Leste', code: 'TLS', iso2: 'TL', flag: '🇹🇱', currency: 'USD' },
  { name: 'Togo', code: 'TGO', iso2: 'TG', flag: '🇹🇬', currency: 'XOF' },
  { name: 'Tonga', code: 'TON', iso2: 'TO', flag: '🇹🇴', currency: 'TOP' },
  { name: 'Trinidad and Tobago', code: 'TTO', iso2: 'TT', flag: '🇹🇹', currency: 'TTD' },
  { name: 'Tunisia', code: 'TUN', iso2: 'TN', flag: '🇹🇳', currency: 'TND' },
  { name: 'Turkey', code: 'TUR', iso2: 'TR', flag: '🇹🇷', currency: 'TRY' },
  { name: 'Turkmenistan', code: 'TKM', iso2: 'TM', flag: '🇹🇲', currency: 'TMT' },
  { name: 'Tuvalu', code: 'TUV', iso2: 'TV', flag: '🇹🇻', currency: 'AUD' },
  { name: 'Uganda', code: 'UGA', iso2: 'UG', flag: '🇺🇬', currency: 'UGX' },
  { name: 'Ukraine', code: 'UKR', iso2: 'UA', flag: '🇺🇦', currency: 'UAH' },
  { name: 'United Arab Emirates', code: 'ARE', iso2: 'AE', flag: '🇦🇪', currency: 'AED' },
  { name: 'United Kingdom', code: 'GBR', iso2: 'GB', flag: '🇬🇧', currency: 'GBP' },
  { name: 'United States', code: 'USA', iso2: 'US', flag: '🇺🇸', currency: 'USD' },
  { name: 'Uruguay', code: 'URY', iso2: 'UY', flag: '🇺🇾', currency: 'UYU' },
  { name: 'Uzbekistan', code: 'UZB', iso2: 'UZ', flag: '🇺🇿', currency: 'UZS' },
  { name: 'Vanuatu', code: 'VUT', iso2: 'VU', flag: '🇻🇺', currency: 'VUV' },
  { name: 'Vatican City', code: 'VAT', iso2: 'VA', flag: '🇻🇦', currency: 'EUR' },
  { name: 'Venezuela', code: 'VEN', iso2: 'VE', flag: '🇻🇪', currency: 'VES' },
  { name: 'Vietnam', code: 'VNM', iso2: 'VN', flag: '🇻🇳', currency: 'VND' },
  { name: 'Yemen', code: 'YEM', iso2: 'YE', flag: '🇾🇪', currency: 'YER' },
  { name: 'Zambia', code: 'ZMB', iso2: 'ZM', flag: '🇿🇲', currency: 'ZMW' },
  { name: 'Zimbabwe', code: 'ZWE', iso2: 'ZW', flag: '🇿🇼', currency: 'ZWG' }
];
