export interface CountryData {
  name: string;
  code: string; // ISO3
  iso2: string; // ISO2 for API lookups
  flag: string;
}

export const GLOBAL_COUNTRIES: CountryData[] = [
  { name: 'Afghanistan', code: 'AFG', iso2: 'AF', flag: '🇦🇫' },
  { name: 'Albania', code: 'ALB', iso2: 'AL', flag: '🇦🇱' },
  { name: 'Algeria', code: 'DZA', iso2: 'DZ', flag: '🇩🇿' },
  { name: 'Andorra', code: 'AND', iso2: 'AD', flag: '🇦🇩' },
  { name: 'Angola', code: 'AGO', iso2: 'AO', flag: '🇦🇴' },
  { name: 'Argentina', code: 'ARG', iso2: 'AR', flag: '🇦🇷' },
  { name: 'Armenia', code: 'ARM', iso2: 'AM', flag: '🇦🇲' },
  { name: 'Australia', code: 'AUS', iso2: 'AU', flag: '🇦🇺' },
  { name: 'Austria', code: 'AUT', iso2: 'AT', flag: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZE', iso2: 'AZ', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BHS', iso2: 'BS', flag: '🇧🇸' },
  { name: 'Bahrain', code: 'BHR', iso2: 'BH', flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'BGD', iso2: 'BD', flag: '🇧🇩' },
  { name: 'Barbados', code: 'BRB', iso2: 'BB', flag: '🇧🇧' },
  { name: 'Belarus', code: 'BLR', iso2: 'BY', flag: '🇧🇾' },
  { name: 'Belgium', code: 'BEL', iso2: 'BE', flag: '🇧🇪' },
  { name: 'Belize', code: 'BLZ', iso2: 'BZ', flag: '🇧🇿' },
  { name: 'Benin', code: 'BEN', iso2: 'BJ', flag: '🇧🇯' },
  { name: 'Bhutan', code: 'BTN', iso2: 'BT', flag: '🇧🇹' },
  { name: 'Bolivia', code: 'BOL', iso2: 'BO', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'BIH', iso2: 'BA', flag: '🇧🇦' },
  { name: 'Botswana', code: 'BWA', iso2: 'BW', flag: '🇧🇼' },
  { name: 'Brazil', code: 'BRA', iso2: 'BR', flag: '🇧🇷' },
  { name: 'Brunei', code: 'BRN', iso2: 'BN', flag: '🇧🇳' },
  { name: 'Bulgaria', code: 'BGR', iso2: 'BG', flag: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BFA', iso2: 'BF', flag: '🇧🇫' },
  { name: 'Burundi', code: 'BDI', iso2: 'BI', flag: '🇧🇮' },
  { name: 'Cabo Verde', code: 'CPV', iso2: 'CV', flag: '🇨🇻' },
  { name: 'Cambodia', code: 'KHM', iso2: 'KH', flag: '🇰🇭' },
  { name: 'Cameroon', code: 'CMR', iso2: 'CM', flag: '🇨🇲' },
  { name: 'Canada', code: 'CAN', iso2: 'CA', flag: '🇨🇦' },
  { name: 'Central African Republic', code: 'CAF', iso2: 'CF', flag: '🇨🇫' },
  { name: 'Chad', code: 'TCD', iso2: 'TD', flag: '🇹🇩' },
  { name: 'Chile', code: 'CHL', iso2: 'CL', flag: '🇨🇱' },
  { name: 'China', code: 'CHN', iso2: 'CN', flag: '🇨🇳' },
  { name: 'Colombia', code: 'COL', iso2: 'CO', flag: '🇨🇴' },
  { name: 'Comoros', code: 'COM', iso2: 'KM', flag: '🇰🇲' },
  { name: 'Congo', code: 'COG', iso2: 'CG', flag: '🇨🇬' },
  { name: 'Costa Rica', code: 'CRI', iso2: 'CR', flag: '🇨🇷' },
  { name: 'Croatia', code: 'HRV', iso2: 'HR', flag: '🇭🇷' },
  { name: 'Cuba', code: 'CUB', iso2: 'CU', flag: '🇨🇺' },
  { name: 'Cyprus', code: 'CYP', iso2: 'CY', flag: '🇨🇾' },
  { name: 'Czechia', code: 'CZE', iso2: 'CZ', flag: '🇨🇿' },
  { name: 'Denmark', code: 'DNK', iso2: 'DK', flag: '🇩🇰' },
  { name: 'Djibouti', code: 'DJI', iso2: 'DJ', flag: '🇩🇯' },
  { name: 'Dominica', code: 'DMA', iso2: 'DM', flag: '🇩🇲' },
  { name: 'Dominican Republic', code: 'DOM', iso2: 'DO', flag: '🇩🇴' },
  { name: 'Ecuador', code: 'ECU', iso2: 'EC', flag: '🇪🇨' },
  { name: 'Egypt', code: 'EGY', iso2: 'EG', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'SLV', iso2: 'SV', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', code: 'GNQ', iso2: 'GQ', flag: '🇬🇶' },
  { name: 'Eritrea', code: 'ERI', iso2: 'ER', flag: '🇪🇷' },
  { name: 'Estonia', code: 'EST', iso2: 'EE', flag: '🇪🇪' },
  { name: 'Eswatini', code: 'SWZ', iso2: 'SZ', flag: '🇸🇿' },
  { name: 'Ethiopia', code: 'ETH', iso2: 'ET', flag: '🇪🇹' },
  { name: 'Fiji', code: 'FJI', iso2: 'FJ', flag: '🇫🇯' },
  { name: 'Finland', code: 'FIN', iso2: 'FI', flag: '🇫🇮' },
  { name: 'France', code: 'FRA', iso2: 'FR', flag: '🇫🇷' },
  { name: 'Gabon', code: 'GAB', iso2: 'GA', flag: '🇬🇦' },
  { name: 'Gambia', code: 'GMB', iso2: 'GM', flag: '🇬🇲' },
  { name: 'Georgia', code: 'GEO', iso2: 'GE', flag: '🇬🇪' },
  { name: 'Germany', code: 'DEU', iso2: 'DE', flag: '🇩🇪' },
  { name: 'Ghana', code: 'GHA', iso2: 'GH', flag: '🇬🇭' },
  { name: 'Greece', code: 'GRC', iso2: 'GR', flag: '🇬🇷' },
  { name: 'Grenada', code: 'GRD', iso2: 'GD', flag: '🇬🇩' },
  { name: 'Guatemala', code: 'GTM', iso2: 'GT', flag: '🇬🇹' },
  { name: 'Guinea', code: 'GIN', iso2: 'GN', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', code: 'GNB', iso2: 'GW', flag: '🇬🇼' },
  { name: 'Guyana', code: 'GUY', iso2: 'GY', flag: '🇬🇾' },
  { name: 'Haiti', code: 'HTI', iso2: 'HT', flag: '🇭🇹' },
  { name: 'Honduras', code: 'HND', iso2: 'HN', flag: '🇭🇳' },
  { name: 'Hungary', code: 'HUN', iso2: 'HU', flag: '🇭🇺' },
  { name: 'Iceland', code: 'ISL', iso2: 'IS', flag: '🇮🇸' },
  { name: 'India', code: 'IND', iso2: 'IN', flag: '🇮🇳' },
  { name: 'Indonesia', code: 'IDN', iso2: 'ID', flag: '🇮🇩' },
  { name: 'Iran', code: 'IRN', iso2: 'IR', flag: '🇮🇷' },
  { name: 'Iraq', code: 'IRQ', iso2: 'IQ', flag: '🇮🇶' },
  { name: 'Ireland', code: 'IRL', iso2: 'IE', flag: '🇮🇪' },
  { name: 'Israel', code: 'ISR', iso2: 'IL', flag: '🇮🇱' },
  { name: 'Italy', code: 'ITA', iso2: 'IT', flag: '🇮🇹' },
  { name: 'Jamaica', code: 'JAM', iso2: 'JM', flag: '🇯🇲' },
  { name: 'Japan', code: 'JPN', iso2: 'JP', flag: '🇯🇵' },
  { name: 'Jordan', code: 'JOR', iso2: 'JO', flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KAZ', iso2: 'KZ', flag: '🇰🇿' },
  { name: 'Kenya', code: 'KEN', iso2: 'KE', flag: '🇰🇪' },
  { name: 'Kiribati', code: 'KIR', iso2: 'KI', flag: '🇰🇮' },
  { name: 'Kuwait', code: 'KWT', iso2: 'KW', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KGZ', iso2: 'KG', flag: '🇰🇬' },
  { name: 'Laos', code: 'LAO', iso2: 'LA', flag: '🇱🇦' },
  { name: 'Latvia', code: 'LVA', iso2: 'LV', flag: '🇱🇻' },
  { name: 'Lebanon', code: 'LBN', iso2: 'LB', flag: '🇱🇧' },
  { name: 'Lesotho', code: 'LSO', iso2: 'LS', flag: '🇱🇸' },
  { name: 'Liberia', code: 'LBR', iso2: 'LR', flag: '🇱🇷' },
  { name: 'Libya', code: 'LBY', iso2: 'LY', flag: '🇱🇾' },
  { name: 'Liechtenstein', code: 'LIE', iso2: 'LI', flag: '🇱🇮' },
  { name: 'Lithuania', code: 'LTU', iso2: 'LT', flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'LUX', iso2: 'LU', flag: '🇱🇺' },
  { name: 'Madagascar', code: 'MDG', iso2: 'MG', flag: '🇲🇬' },
  { name: 'Malawi', code: 'MWI', iso2: 'MW', flag: '🇲🇼' },
  { name: 'Malaysia', code: 'MYS', iso2: 'MY', flag: '🇲🇾' },
  { name: 'Maldives', code: 'MDV', iso2: 'MV', flag: '🇲🇻' },
  { name: 'Mali', code: 'MLI', iso2: 'ML', flag: '🇲🇱' },
  { name: 'Malta', code: 'MLT', iso2: 'MT', flag: '🇲🇹' },
  { name: 'Marshall Islands', code: 'MHL', iso2: 'MH', flag: '🇲🇭' },
  { name: 'Mauritania', code: 'MRT', iso2: 'MR', flag: '🇲🇷' },
  { name: 'Mauritius', code: 'MUS', iso2: 'MU', flag: '🇲🇺' },
  { name: 'Mexico', code: 'MEX', iso2: 'MX', flag: '🇲🇽' },
  { name: 'Micronesia', code: 'FSM', iso2: 'FM', flag: '🇫🇲' },
  { name: 'Moldova', code: 'MDA', iso2: 'MD', flag: '🇲🇩' },
  { name: 'Monaco', code: 'MCO', iso2: 'MC', flag: '🇲🇨' },
  { name: 'Mongolia', code: 'MNG', iso2: 'MN', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'MNE', iso2: 'ME', flag: '🇲🇪' },
  { name: 'Morocco', code: 'MAR', iso2: 'MA', flag: '🇲🇦' },
  { name: 'Mozambique', code: 'MOZ', iso2: 'MZ', flag: '🇲🇿' },
  { name: 'Myanmar', code: 'MMR', iso2: 'MM', flag: '🇲🇲' },
  { name: 'Namibia', code: 'NAM', iso2: 'NA', flag: '🇳🇦' },
  { name: 'Nauru', code: 'NRU', iso2: 'NR', flag: '🇳🇷' },
  { name: 'Nepal', code: 'NPL', iso2: 'NP', flag: '🇳🇵' },
  { name: 'Netherlands', code: 'NLD', iso2: 'NL', flag: '🇳🇱' },
  { name: 'New Zealand', code: 'NZL', iso2: 'NZ', flag: '🇳🇿' },
  { name: 'Nicaragua', code: 'NIC', iso2: 'NI', flag: '🇳🇮' },
  { name: 'Niger', code: 'NER', iso2: 'NE', flag: '🇳🇪' },
  { name: 'Nigeria', code: 'NGA', iso2: 'NG', flag: '🇳🇬' },
  { name: 'North Korea', code: 'PRK', iso2: 'KP', flag: '🇰🇵' },
  { name: 'North Macedonia', code: 'MKD', iso2: 'MK', flag: '🇲🇰' },
  { name: 'Norway', code: 'NOR', iso2: 'NO', flag: '🇳🇴' },
  { name: 'Oman', code: 'OMN', iso2: 'OM', flag: '🇴🇲' },
  { name: 'Pakistan', code: 'PAK', iso2: 'PK', flag: '🇵🇰' },
  { name: 'Palau', code: 'PLW', iso2: 'PW', flag: '🇵🇼' },
  { name: 'Palestine', code: 'PSE', iso2: 'PS', flag: '🇵🇸' },
  { name: 'Panama', code: 'PAN', iso2: 'PA', flag: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PNG', iso2: 'PG', flag: '🇵🇬' },
  { name: 'Paraguay', code: 'PRY', iso2: 'PY', flag: '🇵🇾' },
  { name: 'Peru', code: 'PER', iso2: 'PE', flag: '🇵🇪' },
  { name: 'Philippines', code: 'PHL', iso2: 'PH', flag: '🇵🇭' },
  { name: 'Poland', code: 'POL', iso2: 'PL', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PRT', iso2: 'PT', flag: '🇵🇹' },
  { name: 'Qatar', code: 'QAT', iso2: 'QA', flag: '🇶🇦' },
  { name: 'Romania', code: 'ROU', iso2: 'RO', flag: '🇷🇴' },
  { name: 'Russia', code: 'RUS', iso2: 'RU', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'RWA', iso2: 'RW', flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', code: 'KNA', iso2: 'KN', flag: '🇰🇳' },
  { name: 'Saint Lucia', code: 'LCA', iso2: 'LC', flag: '🇱🇨' },
  { name: 'Samoa', code: 'WSM', iso2: 'WS', flag: '🇼🇸' },
  { name: 'San Marino', code: 'SMR', iso2: 'SM', flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', code: 'STP', iso2: 'ST', flag: '🇸🇹' },
  { name: 'Saudi Arabia', code: 'SAU', iso2: 'SA', flag: '🇸🇦' },
  { name: 'Senegal', code: 'SEN', iso2: 'SN', flag: '🇸🇳' },
  { name: 'Serbia', code: 'SRB', iso2: 'RS', flag: '🇷🇸' },
  { name: 'Seychelles', code: 'SYC', iso2: 'SC', flag: '🇸🇨' },
  { name: 'Sierra Leone', code: 'SLE', iso2: 'SL', flag: '🇸🇱' },
  { name: 'Singapore', code: 'SGP', iso2: 'SG', flag: '🇸🇬' },
  { name: 'Slovakia', code: 'SVK', iso2: 'SK', flag: '🇸🇰' },
  { name: 'Slovenia', code: 'SVN', iso2: 'SI', flag: '🇸🇮' },
  { name: 'Solomon Islands', code: 'SLB', iso2: 'SB', flag: '🇸🇧' },
  { name: 'Somalia', code: 'SOM', iso2: 'SO', flag: '🇸🇴' },
  { name: 'South Africa', code: 'ZAF', iso2: 'ZA', flag: '🇿🇦' },
  { name: 'South Korea', code: 'KOR', iso2: 'KR', flag: '🇰🇷' },
  { name: 'South Sudan', code: 'SSD', iso2: 'SS', flag: '🇸🇸' },
  { name: 'Spain', code: 'ESP', iso2: 'ES', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LKA', iso2: 'LK', flag: '🇱🇰' },
  { name: 'Sudan', code: 'SDN', iso2: 'SD', flag: '🇸🇩' },
  { name: 'Suriname', code: 'SUR', iso2: 'SR', flag: '🇸🇷' },
  { name: 'Sweden', code: 'SWE', iso2: 'SE', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'CHE', iso2: 'CH', flag: '🇨🇭' },
  { name: 'Syria', code: 'SYR', iso2: 'SY', flag: '🇸🇾' },
  { name: 'Taiwan', code: 'TWN', iso2: 'TW', flag: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJK', iso2: 'TJ', flag: '🇹🇯' },
  { name: 'Tanzania', code: 'TZA', iso2: 'TZ', flag: '🇹🇿' },
  { name: 'Thailand', code: 'THA', iso2: 'TH', flag: '🇹🇭' },
  { name: 'Timor-Leste', code: 'TLS', iso2: 'TL', flag: '🇹🇱' },
  { name: 'Togo', code: 'TGO', iso2: 'TG', flag: '🇹🇬' },
  { name: 'Tonga', code: 'TON', iso2: 'TO', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: 'TTO', iso2: 'TT', flag: '🇹🇹' },
  { name: 'Tunisia', code: 'TUN', iso2: 'TN', flag: '🇹🇳' },
  { name: 'Turkey', code: 'TUR', iso2: 'TR', flag: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TKM', iso2: 'TM', flag: '🇹🇲' },
  { name: 'Tuvalu', code: 'TUV', iso2: 'TV', flag: '🇹🇻' },
  { name: 'Uganda', code: 'UGA', iso2: 'UG', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'UKR', iso2: 'UA', flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'ARE', iso2: 'AE', flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'GBR', iso2: 'GB', flag: '🇬🇧' },
  { name: 'United States', code: 'USA', iso2: 'US', flag: '🇺🇸' },
  { name: 'Uruguay', code: 'URY', iso2: 'UY', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZB', iso2: 'UZ', flag: '🇺🇿' },
  { name: 'Vanuatu', code: 'VUT', iso2: 'VU', flag: '🇻🇺' },
  { name: 'Vatican City', code: 'VAT', iso2: 'VA', flag: '🇻🇦' },
  { name: 'Venezuela', code: 'VEN', iso2: 'VE', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'VNM', iso2: 'VN', flag: '🇻🇳' },
  { name: 'Yemen', code: 'YEM', iso2: 'YE', flag: '🇾🇪' },
  { name: 'Zambia', code: 'ZMB', iso2: 'ZM', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZWE', iso2: 'ZW', flag: '🇿🇼' }
];
